---
title: "simpleEnsembleGuide"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simpleEnsembleGuide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(simpleEnsembleGroup8)
```

```{r}

# continuous
data(mtcars)
X <- mtcars[, -which(names(mtcars) == "mpg")]
y <- mtcars$mpg  # For gaussian; use a binary response for 'binomial'
y <- as.numeric(y)
model_randomfr = fit_random_forest_model(y, X, model_type = 'gaussian')
# model_randomfr
# predict_model(model_randomfr, X)


# model_linear
model_list <- c("fit_linear_model", "fit_lasso_model", "fit_random_forest_model")
# model_list <- c("fit_lasso_model")
results <- ensemble_model_fitting(X, y, model_type = 'gaussian', model_list = model_list)
results$combined_predictions
print(results)

```



```{r}
X <- iris[iris$Species != "setosa", c("Sepal.Length", "Sepal.Width")]
y <- as.numeric(iris$Species[iris$Species != "setosa"] == "versicolor")
model <- fit_random_forest_model(y, X, model_type = 'binomial')
# model
# predict_model(model, X, type = 'probabilities')



model_list <- c("fit_logistic_model", "fit_lasso_model", "fit_random_forest_model")
# model_list <- c("fit_logistic_model")
results <- ensemble_model_fitting(X, y, model_type = 'binomial', model_list = model_list)
print(results)

```


```{r}
# Generating sample data
set.seed(123) # for reproducibility
num_samples <- 100
numeric_data <- rnorm(num_samples, mean = 50, sd = 10)
factor_levels <- c("A", "B", "C")
factor_data <- sample(factor_levels, num_samples, replace = TRUE)
binary_data <- sample(c(0, 1), num_samples, replace = TRUE)
sample_df <- data.frame(Numeric_Column = numeric_data,
                        Factor_Column = as.factor(factor_data),
                        binary_column=binary_data)
head(sample_df)
```

#our model
```{r}
model3<-fit_linear_model(sample_df$Numeric_Column,sample_df[-1])
model3
```
#built in
```{r}
model <- lm(sample_df$Numeric_Column ~ ., data = sample_df[, -1])
summary(model)
```


```


```{r}
results
```

